// src/_mock/user.js

export const users = [
  {
    id: 1,
    name: 'User 1',
    status: 'Active',
    company: 'Company A',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 2,
    name: 'User 2',
    role: 'Role 2',
    status: 'Inactive',
    company: 'Company B',
    avatarUrl: 'url_to_avatar',
    isVerified: false,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 3,
    name: 'User 3',
    role: 'Role 3',
    status: 'Active',
    company: 'Company C',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 4,
    name: 'User 4',
    role: 'Role 4',
    status: 'Active',
    company: 'Company D',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 5,
    name: 'User 5',
    role: 'Role 5',
    status: 'Active',
    company: 'Company E',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 6,
    name: 'User 6',
    role: 'Role 6',
    status: 'Active',
    company: 'Company F',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 7,
    name: 'User 7',
    role: 'Role 7',
    status: 'Active',
    company: 'Company G',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 8,
    name: 'User 8',
    role: 'Role 8',
    status: 'Active',
    company: 'Company H',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 9,
    name: 'User 9',
    role: 'Role 9',
    status: 'Active',
    company: 'Company I',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  },
  {
    id: 10,
    name: 'User 10',
    role: 'Role 10',
    status: 'Active',
    company: 'Company J',
    avatarUrl: 'url_to_avatar',
    isVerified: true,
    day1: 'Data for Day 1', 
    day2: 'Data for Day 2',
  }
];
